eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#spring.boot.admin.url: http://localhost:8989

spring:
	cloud:
		config:
			uri: http://localhost:8888

management:
	security:
		enabled: false

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888
  application:
    name: event-service

eureka:
  instance:
    hostname: event-service
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/
endpoints:
 shutdown:
    enabled: true

management:
  security:
    enabled: false

#spring.boot.admin.url: http://turbine-service:8989
management.security.enabled: false


#spring.cloud.stream.bindings.output.destination=patients

#spring.cloud.stream.bindings.input.durableSubscription=true

#security.oauth2.resource.userInfoUri=http://localhost:9191/uaa/user