eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


security:
  basic:
    enabled: false

spring:
  cloud:
    config:
      uri: http://localhost:8888

management:
  security:
    enabled: false


logging:
  level:
    org:
      springframework:
                  web:  INFO
      hibernate: ERROR
  config: classpath:log4j2.properties


---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://config-server:8888
  application:
    name: gateway-service

eureka:
  instance:
    hostname: gateway-service
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/
endpoints:
 shutdown:
    enabled: true

management:
  security:
    enabled: false

#spring.boot.admin.url: http://turbine-service:8989
management.security.enabled: false
