eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


security:
  basic:
    enabled: false

management:
  security:
    enabled: false


logging:
  level:
    org:
      springframework:
                  web:  INFO
      hibernate: ERROR
  config: classpath:log4j2.properties


---
spring:
  profiles: docker

eureka:
  instance:
    hostname: event-service
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/
endpoints:
 shutdown:
    enabled: true

#spring.boot.admin.url: http://turbine-service:8989
management.security.enabled: false
