spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/olha_database
    username: docker
    password: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: olha-data-service

logging:
  level:
    org:
      hibernate: ERROR
      
server:
  port: ${PORT:8181}

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


---
spring:
  profiles: docker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/olha_database
    username: docker
    password: docker
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: olha-data-serivce

logging:
  level:
    org:
      hibernate: ERROR
server:
  port: ${PORT:8181}


eureka:
  instance:
    hostname: olha-data-serivce
  client:
   registerWithEureka: true
   fetchRegistry: true
   serviceUrl:
           defaultZone: http://eureka-server:8761/eureka/ 

